name: Yelb CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v2
        with:
          dockerfile: ./yelb-ui/Dockerfile

scan:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Docker Scout Scan
        run: |
          docker build -t yelb-ui ./yelb-ui
          docker scout quickview yelb-ui
       # env:
        #  DOCKER_SCOUT_API_TOKEN: ${{ secrets.DOCKER_SCOUT_API_TOKEN }}

